swagger: '2.0'
info:
  description: Product service API documentation
  version: 1.0.0
  title: Product Service
host: x1az9zsxk9.execute-api.eu-west-1.amazonaws.com
basePath: /dev
schemes:
- https
- http

tags:
- name: products
  description: get info about your products

paths:
  /products:
    get:
      tags:
      - products
      summary: Get all available products
      operationId: getProducts
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
  /products/{id}:
    get:
      tags:
      - products
      summary: "Get product by id"
      operationId: "getProductById"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "id"
        in: "path"
        description: "Product Id"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        404:
          description: "Product not found"
definitions:
  Product:
    type: object
    required:
    - id
    - title
    properties:
      id:
        type: string
        example: 1
      title:
        type: string
        example: Slam Ball
      description:
        type: string
        example: Slamm Ball 40kg
      price:
        type: number
        example: 100
      count:
        type: number
        example: 12
      img:
        type: string
        description: image url
    xml:
      name: Product